### ISSUE TITLE
UnexpectedEof panic while idle

### ISSUE THREAD

**Issue by Synesso** [astroband/astrocore#26]
With `rustc 1.38.0-nightly (69656fa4c 2019-07-13)`

Executing `RUST_BACKTRACE=1 RUST_LOG="astrocore=info" RUSTFLAGS=-Awarnings cargo run`

After less than a minute:

```[2019-08-14T11:58:04Z INFO  astrocore::overlay::peer] [Overlay] Authentication completed for peer 13.114.104.43:11625
thread 'pool-thread-#8' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }', src/libcore/result.rs:1051:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::unwrap
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libcore/result.rs:852
  12: <astrocore::overlay::peer::Peer as astrocore::overlay::peer::PeerInterface>::receive_message
             at src/overlay/peer.rs:417
  13: <astrocore::actors::peer::PeerActor as riker::actor::actor::Actor>::receive
             at src/actors/peer.rs:46
  14: <alloc::boxed::Box<A> as riker::actor::actor::Actor>::receive
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/riker-0.2.4/src/actor/actor.rs:239
  15: riker::kernel::mailbox::handle_actor_msg
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/riker-0.2.4/src/kernel/mailbox.rs:304
  16: riker::kernel::mailbox::handle_msg
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/riker-0.2.4/src/kernel/mailbox.rs:290
  17: riker::kernel::mailbox::process_msgs
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/riker-0.2.4/src/kernel/mailbox.rs:211
  18: riker::kernel::mailbox::run_mailbox
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/riker-0.2.4/src/kernel/mailbox.rs:182
  19: riker::kernel::kernel::Kernel<Msg,Dis>::unpark_actor::{{closure}}
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/riker-0.2.4/src/kernel/kernel.rs:253
  20: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/future.rs:42
  21: std::future::set_task_context
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/future.rs:78
  22: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/future.rs:42
  23: <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/panic.rs:334
  24: <futures_util::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/future/catch_unwind.rs:29
  25: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/panic.rs:315
  26: std::panicking::try::do_call
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/panicking.rs:296
  27: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  28: std::panicking::try
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/panicking.rs:275
  29: std::panic::catch_unwind
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/panic.rs:394
  30: <futures_util::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/future/catch_unwind.rs:29
  31: std::future::poll_with_tls_context::{{closure}}
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/future.rs:120
  32: std::future::get_task_context
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/future.rs:110
  33: std::future::poll_with_tls_context
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/future.rs:120
  34: riker::kernel::kernel::Kernel<Msg,Dis>::unpark_actor::{{closure}}
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/riker-0.2.4/src/kernel/kernel.rs:257
  35: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/future.rs:42
  36: std::future::set_task_context
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/future.rs:78
  37: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/libstd/future.rs:42
  38: <futures_core::future::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.17/src/future/future_obj.rs:80
  39: <futures_core::future::future_obj::FutureObj<T> as core::future::future::Future>::poll
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.17/src/future/future_obj.rs:131
  40: futures_util::future::FutureExt::poll_unpin
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/future/mod.rs:532
  41: futures_executor::thread_pool::Task::run
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.17/src/thread_pool.rs:309
  42: futures_executor::thread_pool::PoolState::work
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.17/src/thread_pool.rs:143
  43: futures_executor::thread_pool::ThreadPoolBuilder::create::{{closure}}
             at /Users/jmawson/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-preview-0.3.0-alpha.17/src/thread_pool.rs:271
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.```

**Comment by Arkweid** [comment]
Ye, it happens here: 
https://github.com/astroband/astrocore/blob/master/src/overlay/peer.rs#L417
For great safety, all `unwrap()` should be eliminated :) This `panic()` happens because message body don't match with header.
